name: Deploy Sentinal
run-name: CI for ${{ github.event.repository.name }} - ${{ github.event_name }} by @${{ github.actor }} - ${{ github.run_id }}

on:
  push:
    paths:
      - "scripts/**"
      - ".github/workflows/deploy-sentinal.yml"

jobs:
  Scan_Secrets:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified

  Deploy_Sentinal:
    runs-on: windows-latest
    needs: Scan_Secrets
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Azure Login action
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Enable Sentinel
        uses: azure/powershell@v2
        env:
          working_directory: "${{ github.workspace }}/scripts/"
        with:
          azPSVersion: "latest"
          inlineScript: |
            ./scripts/enableSentinal.ps1 -WorkingDirectoryParam $Env:working_directory
